coreSingleMessageConsumer:
  groupId: product.kafka-partition-scaler-example.topic.0.core
  name: product.kafka-partition-scaler-example.topic.0
  retry: product.kafka-partition-scaler-example.0.core.retry.0
  error: product.kafka-partition-scaler-example.error.0
  maxProcessingTime: "1s"
  retryCount: 3
  cluster: "stretch"